//C:\Users\t-kevimi\\Documents\\LuaTests\Lua Files for Testing\InvalidProgramsAsStrings.lua\r\nusing LanguageModel.Tests.TestGeneration;
using LanguageService;
using LanguageModel.Tests.TestGeneration;
using Xunit;
namespace LanguageModel.Tests.GeneratedTestFiles
{
    class Generated_20
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.Number);
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.TableConstructorExp);
                            {
                                t.N(SyntaxKind.OpenCurlyBrace);
                                t.N(SyntaxKind.FieldList);
                                {
                                    t.N(SyntaxKind.ExpField);
                                    {
                                        t.N(SyntaxKind.SimpleExpression);
                                        {
                                            t.N(SyntaxKind.Number);
                                        }
                                    }
                                    t.N(SyntaxKind.Comma);
                                    t.N(SyntaxKind.ExpField);
                                    {
                                        t.N(SyntaxKind.SimpleExpression);
                                        {
                                            t.N(SyntaxKind.Number);
                                        }
                                    }
                                    t.N(SyntaxKind.Comma);
                                }
                                t.N(SyntaxKind.CloseCurlyBrace);
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.FunctionDef);
                            {
                                t.N(SyntaxKind.FunctionKeyword);
                                t.N(SyntaxKind.FuncBodyNode);
                                {
                                    t.N(SyntaxKind.OpenParen);
                                    t.N(SyntaxKind.NameListPar);
                                    {
                                        t.N(SyntaxKind.NameList);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                            t.N(SyntaxKind.Comma);
                                            t.N(SyntaxKind.Identifier);
                                            t.N(SyntaxKind.Comma);
                                            t.N(SyntaxKind.Identifier);
                                        }
                                    }
                                    t.N(SyntaxKind.CloseParen);
                                    t.N(SyntaxKind.BlockNode);
                                    {
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.SimpleExpression);
                                                {
                                                    t.N(SyntaxKind.Number);
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.FunctionCallStatementNode);
                                        {
                                            t.N(SyntaxKind.NameVar);
                                            {
                                                t.N(SyntaxKind.Identifier);
                                            }
                                            t.N(SyntaxKind.Colon);
                                            t.N(SyntaxKind.Identifier);
                                            t.N(SyntaxKind.ParenArg);
                                            {
                                                t.N(SyntaxKind.OpenParen);
                                                t.N(SyntaxKind.ExpList);
                                                t.N(SyntaxKind.CloseParen);
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.DotVar);
                                                {
                                                    t.N(SyntaxKind.NameVar);
                                                    {
                                                        t.N(SyntaxKind.Identifier);
                                                    }
                                                    t.N(SyntaxKind.Dot);
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.MissingToken);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.ParenPrefixExp);
                                                {
                                                    t.N(SyntaxKind.OpenParen);
                                                    t.N(SyntaxKind.MissingToken);
                                                    {
                                                        t.N(SyntaxKind.MissingToken);
                                                    }
                                                    t.N(SyntaxKind.CloseParen);
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.FunctionDef);
                                                {
                                                    t.N(SyntaxKind.FunctionKeyword);
                                                    t.N(SyntaxKind.FuncBodyNode);
                                                    {
                                                        t.N(SyntaxKind.OpenParen);
                                                        t.N(SyntaxKind.NameListPar);
                                                        {
                                                            t.N(SyntaxKind.NameList);
                                                        }
                                                        t.N(SyntaxKind.CloseParen);
                                                        t.N(SyntaxKind.BlockNode);
                                                        {
                                                            t.N(SyntaxKind.ReturnStatementNode);
                                                            {
                                                                t.N(SyntaxKind.ReturnKeyword);
                                                                t.N(SyntaxKind.ExpList);
                                                            }
                                                        }
                                                        t.N(SyntaxKind.EndKeyword);
                                                    }
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.FunctionDef);
                                                {
                                                    t.N(SyntaxKind.FunctionKeyword);
                                                    t.N(SyntaxKind.FuncBodyNode);
                                                    {
                                                        t.N(SyntaxKind.OpenParen);
                                                        t.N(SyntaxKind.NameListPar);
                                                        {
                                                            t.N(SyntaxKind.NameList);
                                                        }
                                                        t.N(SyntaxKind.CloseParen);
                                                        t.N(SyntaxKind.BlockNode);
                                                        {
                                                            t.N(SyntaxKind.ReturnStatementNode);
                                                            {
                                                                t.N(SyntaxKind.ReturnKeyword);
                                                                t.N(SyntaxKind.ExpList);
                                                            }
                                                        }
                                                        t.N(SyntaxKind.EndKeyword);
                                                    }
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.TableConstructorExp);
                                                {
                                                    t.N(SyntaxKind.OpenCurlyBrace);
                                                    t.N(SyntaxKind.FieldList);
                                                    {
                                                        t.N(SyntaxKind.ExpField);
                                                        {
                                                            t.N(SyntaxKind.SimpleExpression);
                                                            {
                                                                t.N(SyntaxKind.Number);
                                                            }
                                                        }
                                                        t.N(SyntaxKind.Comma);
                                                    }
                                                    t.N(SyntaxKind.CloseCurlyBrace);
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.FunctionDef);
                                                {
                                                    t.N(SyntaxKind.FunctionKeyword);
                                                    t.N(SyntaxKind.FuncBodyNode);
                                                    {
                                                        t.N(SyntaxKind.MissingToken);
                                                        t.N(SyntaxKind.NameListPar);
                                                        {
                                                            t.N(SyntaxKind.NameList);
                                                        }
                                                        t.N(SyntaxKind.MissingToken);
                                                        t.N(SyntaxKind.BlockNode);
                                                        {
                                                            t.N(SyntaxKind.ReturnStatementNode);
                                                            {
                                                                t.N(SyntaxKind.ReturnKeyword);
                                                                t.N(SyntaxKind.ExpList);
                                                            }
                                                        }
                                                        t.N(SyntaxKind.EndKeyword);
                                                    }
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.FunctionDef);
                                                {
                                                    t.N(SyntaxKind.FunctionKeyword);
                                                    t.N(SyntaxKind.FuncBodyNode);
                                                    {
                                                        t.N(SyntaxKind.MissingToken);
                                                        t.N(SyntaxKind.NameListPar);
                                                        {
                                                            t.N(SyntaxKind.NameList);
                                                            {
                                                                t.N(SyntaxKind.Identifier);
                                                            }
                                                        }
                                                        t.N(SyntaxKind.MissingToken);
                                                        t.N(SyntaxKind.BlockNode);
                                                        {
                                                            t.N(SyntaxKind.GlobalFunctionStatementNode);
                                                            {
                                                                t.N(SyntaxKind.FunctionKeyword);
                                                                t.N(SyntaxKind.FuncNameNode);
                                                                {
                                                                    t.N(SyntaxKind.MissingToken);
                                                                    t.N(SyntaxKind.DotSeparatedNameList);
                                                                }
                                                                t.N(SyntaxKind.FuncBodyNode);
                                                                {
                                                                    t.N(SyntaxKind.MissingToken);
                                                                    t.N(SyntaxKind.NameListPar);
                                                                    {
                                                                        t.N(SyntaxKind.NameList);
                                                                    }
                                                                    t.N(SyntaxKind.MissingToken);
                                                                    t.N(SyntaxKind.BlockNode);
                                                                    t.N(SyntaxKind.EndKeyword);
                                                                }
                                                            }
                                                        }
                                                        t.N(SyntaxKind.EndKeyword);
                                                    }
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.TableConstructorExp);
                                                {
                                                    t.N(SyntaxKind.OpenCurlyBrace);
                                                    t.N(SyntaxKind.FieldList);
                                                    {
                                                        t.N(SyntaxKind.AssignmentField);
                                                        {
                                                            t.N(SyntaxKind.Identifier);
                                                            t.N(SyntaxKind.AssignmentOperator);
                                                            t.N(SyntaxKind.TableConstructorExp);
                                                            {
                                                                t.N(SyntaxKind.OpenCurlyBrace);
                                                                t.N(SyntaxKind.FieldList);
                                                                {
                                                                    t.N(SyntaxKind.ExpField);
                                                                    {
                                                                        t.N(SyntaxKind.NameVar);
                                                                        {
                                                                            t.N(SyntaxKind.Identifier);
                                                                        }
                                                                    }
                                                                    t.N(SyntaxKind.Comma);
                                                                    t.N(SyntaxKind.ExpField);
                                                                    {
                                                                        t.N(SyntaxKind.NameVar);
                                                                        {
                                                                            t.N(SyntaxKind.Identifier);
                                                                        }
                                                                    }
                                                                    t.N(SyntaxKind.Comma);
                                                                    t.N(SyntaxKind.ExpField);
                                                                    {
                                                                        t.N(SyntaxKind.NameVar);
                                                                        {
                                                                            t.N(SyntaxKind.Identifier);
                                                                        }
                                                                    }
                                                                }
                                                                t.N(SyntaxKind.CloseCurlyBrace);
                                                            }
                                                        }
                                                    }
                                                    t.N(SyntaxKind.MissingToken);
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.TableConstructorExp);
                                                {
                                                    t.N(SyntaxKind.OpenCurlyBrace);
                                                    t.N(SyntaxKind.FieldList);
                                                    {
                                                        t.N(SyntaxKind.ExpField);
                                                        {
                                                            t.N(SyntaxKind.NameVar);
                                                            {
                                                                t.N(SyntaxKind.Identifier);
                                                            }
                                                        }
                                                    }
                                                    t.N(SyntaxKind.CloseCurlyBrace);
                                                }
                                            }
                                        }
                                        t.N(SyntaxKind.AssignmentStatementNode);
                                        {
                                            t.N(SyntaxKind.VarList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                            }
                                            t.N(SyntaxKind.AssignmentOperator);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.FunctionDef);
                                                {
                                                    t.N(SyntaxKind.FunctionKeyword);
                                                    t.N(SyntaxKind.FuncBodyNode);
                                                    {
                                                        t.N(SyntaxKind.OpenParen);
                                                        t.N(SyntaxKind.NameListPar);
                                                        {
                                                            t.N(SyntaxKind.NameList);
                                                        }
                                                        t.N(SyntaxKind.CloseParen);
                                                        t.N(SyntaxKind.BlockNode);
                                                        {
                                                            t.N(SyntaxKind.ReturnStatementNode);
                                                            {
                                                                t.N(SyntaxKind.ReturnKeyword);
                                                                t.N(SyntaxKind.ExpList);
                                                            }
                                                        }
                                                        t.N(SyntaxKind.EndKeyword);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    t.N(SyntaxKind.MissingToken);
                                }
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.FunctionDef);
                            {
                                t.N(SyntaxKind.FunctionKeyword);
                                t.N(SyntaxKind.FuncBodyNode);
                                {
                                    t.N(SyntaxKind.OpenParen);
                                    t.N(SyntaxKind.NameListPar);
                                    {
                                        t.N(SyntaxKind.NameList);
                                    }
                                    t.N(SyntaxKind.CloseParen);
                                    t.N(SyntaxKind.BlockNode);
                                    {
                                        t.N(SyntaxKind.ReturnStatementNode);
                                        {
                                            t.N(SyntaxKind.ReturnKeyword);
                                            t.N(SyntaxKind.ExpList);
                                        }
                                    }
                                    t.N(SyntaxKind.EndKeyword);
                                }
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.MissingToken);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.String);
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                            t.N(SyntaxKind.Comma);
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.Number);
                            }
                            t.N(SyntaxKind.Comma);
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.Number);
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.MissingToken);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.Number);
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.BinaryOperatorExpression);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.PlusOperator);
                                t.N(SyntaxKind.SimpleExpression);
                                {
                                    t.N(SyntaxKind.Number);
                                }
                            }
                        }
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }
        }
    }
}
