//C:\Users\t-kevimi\\Documents\\LuaTests\Lua Files for Testing\MultipleReturnIf.lua\r\nusing LanguageModel.Tests.TestGeneration;
using LanguageService;
using LanguageModel.Tests.TestGeneration;
using Xunit;
namespace LanguageModel.Tests.GeneratedTestFiles
{
    class Generated_23
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.IfStatementNode);
                    {
                        t.N(SyntaxKind.IfKeyword);
                        t.N(SyntaxKind.BinaryOperatorExpression);
                        {
                            t.N(SyntaxKind.SquareBracketVar);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.OpenBracket);
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.CloseBracket);
                            }
                            t.N(SyntaxKind.NotEqualsOperator);
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.NilKeyValue);
                            }
                        }
                        t.N(SyntaxKind.ThenKeyword);
                        t.N(SyntaxKind.BlockNode);
                        {
                            t.N(SyntaxKind.ReturnStatementNode);
                            {
                                t.N(SyntaxKind.ReturnKeyword);
                                t.N(SyntaxKind.ExpList);
                                {
                                    t.N(SyntaxKind.SquareBracketVar);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                        t.N(SyntaxKind.OpenBracket);
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                        t.N(SyntaxKind.CloseBracket);
                                    }
                                    t.N(SyntaxKind.Comma);
                                    t.N(SyntaxKind.FunctionCallExp);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                        t.N(SyntaxKind.ParenArg);
                                        {
                                            t.N(SyntaxKind.OpenParen);
                                            t.N(SyntaxKind.ExpList);
                                            {
                                                t.N(SyntaxKind.NameVar);
                                                {
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                                t.N(SyntaxKind.Comma);
                                                t.N(SyntaxKind.BinaryOperatorExpression);
                                                {
                                                    t.N(SyntaxKind.NameVar);
                                                    {
                                                        t.N(SyntaxKind.Identifier);
                                                    }
                                                    t.N(SyntaxKind.PlusOperator);
                                                    t.N(SyntaxKind.SimpleExpression);
                                                    {
                                                        t.N(SyntaxKind.Number);
                                                    }
                                                }
                                            }
                                            t.N(SyntaxKind.CloseParen);
                                        }
                                    }
                                }
                            }
                        }
                        t.N(SyntaxKind.EndKeyword);
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }
        }
    }
}
