//C:\Users\t-kevimi\\Documents\\LuaTests\Lua Files for Testing\NestedFunctionDef.lua
using LanguageModel.Tests.TestGeneration;
using LanguageService;
using Xunit;
namespace LanguageModel.Tests.GeneratedTestFiles
{
    class Generated_23
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.GlobalFunctionStatementNode);
                    {
                        t.N(SyntaxKind.FunctionKeyword);
                        t.N(SyntaxKind.FuncNameNode);
                        {
                            t.N(SyntaxKind.Identifier);
                            t.N(SyntaxKind.DotSeparatedNameList);
                        }
                        t.N(SyntaxKind.FuncBodyNode);
                        {
                            t.N(SyntaxKind.OpenParen);
                            t.N(SyntaxKind.NameListPar);
                            {
                                t.N(SyntaxKind.NameList);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                            }
                            t.N(SyntaxKind.CloseParen);
                            t.N(SyntaxKind.BlockNode);
                            {
                                t.N(SyntaxKind.ReturnStatementNode);
                                {
                                    t.N(SyntaxKind.ReturnKeyword);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.FunctionCallExp);
                                        {
                                            t.N(SyntaxKind.NameVar);
                                            {
                                                t.N(SyntaxKind.Identifier);
                                            }
                                            t.N(SyntaxKind.TableConstructorArg);
                                            {
                                                t.N(SyntaxKind.OpenCurlyBrace);
                                                t.N(SyntaxKind.FieldList);
                                                {
                                                    t.N(SyntaxKind.AssignmentField);
                                                    {
                                                        t.N(SyntaxKind.Identifier);
                                                        t.N(SyntaxKind.AssignmentOperator);
                                                        t.N(SyntaxKind.NameVar);
                                                        {
                                                            t.N(SyntaxKind.Identifier);
                                                        }
                                                    }
                                                    t.N(SyntaxKind.Comma);
                                                    t.N(SyntaxKind.AssignmentField);
                                                    {
                                                        t.N(SyntaxKind.Identifier);
                                                        t.N(SyntaxKind.AssignmentOperator);
                                                        t.N(SyntaxKind.FunctionDef);
                                                        {
                                                            t.N(SyntaxKind.FunctionKeyword);
                                                            t.N(SyntaxKind.FuncBodyNode);
                                                            {
                                                                t.N(SyntaxKind.OpenParen);
                                                                t.N(SyntaxKind.NameListPar);
                                                                {
                                                                    t.N(SyntaxKind.NameList);
                                                                }
                                                                t.N(SyntaxKind.CloseParen);
                                                                t.N(SyntaxKind.BlockNode);
                                                                {
                                                                    t.N(SyntaxKind.FunctionCallStatementNode);
                                                                    {
                                                                        t.N(SyntaxKind.NameVar);
                                                                        {
                                                                            t.N(SyntaxKind.Identifier);
                                                                        }
                                                                        t.N(SyntaxKind.ParenArg);
                                                                        {
                                                                            t.N(SyntaxKind.OpenParen);
                                                                            t.N(SyntaxKind.ExpList);
                                                                            {
                                                                                t.N(SyntaxKind.NameVar);
                                                                                {
                                                                                    t.N(SyntaxKind.Identifier);
                                                                                }
                                                                            }
                                                                            t.N(SyntaxKind.CloseParen);
                                                                        }
                                                                    }
                                                                }
                                                                t.N(SyntaxKind.EndKeyword);
                                                            }
                                                        }
                                                    }
                                                }
                                                t.N(SyntaxKind.CloseCurlyBrace);
                                            }
                                        }
                                    }
                                }
                            }
                            t.N(SyntaxKind.EndKeyword);
                        }
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }
        }
    }
}
