//C:\Users\t-kevimi\\Documents\\LuaTests\Lua Files for Testing\ForStatementWithVariables.lua
namespace LanguageModel.Tests.GeneratedTestFiles
{
    using LanguageModel.Tests.TestGeneration;
    using LanguageService;
    using Xunit;

    internal class Generated_10
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.SimpleForStatementNode);
                    {
                        t.N(SyntaxKind.ForKeyword);
                        t.N(SyntaxKind.Identifier);
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.NameVar);
                        {
                            t.N(SyntaxKind.Identifier);
                        }
                        t.N(SyntaxKind.Comma);
                        t.N(SyntaxKind.NameVar);
                        {
                            t.N(SyntaxKind.Identifier);
                        }
                        t.N(SyntaxKind.Comma);
                        t.N(SyntaxKind.NameVar);
                        {
                            t.N(SyntaxKind.Identifier);
                        }
                        t.N(SyntaxKind.DoKeyword);
                        t.N(SyntaxKind.BlockNode);
                        {
                            t.N(SyntaxKind.FunctionCallStatementNode);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.ParenArg);
                                {
                                    t.N(SyntaxKind.OpenParen);
                                    t.N(SyntaxKind.ExpList);
                                    t.N(SyntaxKind.CloseParen);
                                }
                            }
                            t.N(SyntaxKind.SemiColonStatementNode);
                            {
                                t.N(SyntaxKind.Semicolon);
                            }
                        }
                        t.N(SyntaxKind.EndKeyword);
                    }
                    t.N(SyntaxKind.SimpleForStatementNode);
                    {
                        t.N(SyntaxKind.ForKeyword);
                        t.N(SyntaxKind.Identifier);
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.SimpleExpression);
                        {
                            t.N(SyntaxKind.Number);
                        }
                        t.N(SyntaxKind.Comma);
                        t.N(SyntaxKind.FunctionCallExp);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                            t.N(SyntaxKind.ParenArg);
                            {
                                t.N(SyntaxKind.OpenParen);
                                t.N(SyntaxKind.ExpList);
                                {
                                    t.N(SyntaxKind.NameVar);
                                    {
                                        t.N(SyntaxKind.Identifier);
                                    }
                                }
                                t.N(SyntaxKind.CloseParen);
                            }
                        }
                        t.N(SyntaxKind.DoKeyword);
                        t.N(SyntaxKind.BlockNode);
                        {
                            t.N(SyntaxKind.FunctionCallStatementNode);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.ParenArg);
                                {
                                    t.N(SyntaxKind.OpenParen);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                    }
                                    t.N(SyntaxKind.CloseParen);
                                }
                            }
                        }
                        t.N(SyntaxKind.EndKeyword);
                    }
                    t.N(SyntaxKind.SimpleForStatementNode);
                    {
                        t.N(SyntaxKind.ForKeyword);
                        t.N(SyntaxKind.Identifier);
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.SimpleExpression);
                        {
                            t.N(SyntaxKind.Number);
                        }
                        t.N(SyntaxKind.Comma);
                        t.N(SyntaxKind.SimpleExpression);
                        {
                            t.N(SyntaxKind.Number);
                        }
                        t.N(SyntaxKind.Comma);
                        t.N(SyntaxKind.EndKeyword);
                        {
                            t.N(SyntaxKind.MinusOperator);
                            t.N(SyntaxKind.SimpleExpression);
                            {
                                t.N(SyntaxKind.Number);
                            }
                        }
                        t.N(SyntaxKind.DoKeyword);
                        t.N(SyntaxKind.BlockNode);
                        {
                            t.N(SyntaxKind.FunctionCallStatementNode);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.ParenArg);
                                {
                                    t.N(SyntaxKind.OpenParen);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                    }
                                    t.N(SyntaxKind.CloseParen);
                                }
                            }
                        }
                        t.N(SyntaxKind.EndKeyword);
                    }
                    t.N(SyntaxKind.SimpleForStatementNode);
                    {
                        t.N(SyntaxKind.ForKeyword);
                        t.N(SyntaxKind.Identifier);
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.FunctionCallExp);
                        {
                            t.N(SyntaxKind.NameVar);
                            {
                                t.N(SyntaxKind.Identifier);
                            }
                            t.N(SyntaxKind.ParenArg);
                            {
                                t.N(SyntaxKind.OpenParen);
                                t.N(SyntaxKind.ExpList);
                                {
                                    t.N(SyntaxKind.SimpleExpression);
                                    {
                                        t.N(SyntaxKind.TrueKeyValue);
                                    }
                                }
                                t.N(SyntaxKind.CloseParen);
                            }
                        }
                        t.N(SyntaxKind.Comma);
                        t.N(SyntaxKind.SimpleExpression);
                        {
                            t.N(SyntaxKind.Number);
                        }
                        t.N(SyntaxKind.DoKeyword);
                        t.N(SyntaxKind.BlockNode);
                        {
                            t.N(SyntaxKind.FunctionCallStatementNode);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                                t.N(SyntaxKind.ParenArg);
                                {
                                    t.N(SyntaxKind.OpenParen);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                    }
                                    t.N(SyntaxKind.CloseParen);
                                }
                            }
                        }
                        t.N(SyntaxKind.EndKeyword);
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }
        }
    }
}
