//C:\Users\t-kevimi\\Documents\\LuaTests\Lua Files for Testing\VarArgFunction.lua\r\nusing LanguageModel.Tests.TestGeneration;
using LanguageService;
using LanguageModel.Tests.TestGeneration;
using Xunit;
namespace LanguageModel.Tests.GeneratedTestFiles
{
    class Generated_36
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.GlobalFunctionStatementNode);
                    {
                        t.N(SyntaxKind.FunctionKeyword);
                        t.N(SyntaxKind.FuncNameNode);
                        {
                            t.N(SyntaxKind.Identifier);
                            t.N(SyntaxKind.DotSeparatedNameList);
                        }
                        t.N(SyntaxKind.FuncBodyNode);
                        {
                            t.N(SyntaxKind.OpenParen);
                            t.N(SyntaxKind.NameListPar);
                            {
                                t.N(SyntaxKind.NameList);
                                {
                                    t.N(SyntaxKind.Identifier);
                                    t.N(SyntaxKind.Comma);
                                }
                            }
                            t.N(SyntaxKind.CloseParen);
                            t.N(SyntaxKind.BlockNode);
                            {
                                t.N(SyntaxKind.ReturnStatementNode);
                                {
                                    t.N(SyntaxKind.ReturnKeyword);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.DotVar);
                                        {
                                            t.N(SyntaxKind.NameVar);
                                            {
                                                t.N(SyntaxKind.Identifier);
                                            }
                                            t.N(SyntaxKind.Dot);
                                            t.N(SyntaxKind.Identifier);
                                        }
                                    }
                                }
                                t.N(SyntaxKind.AssignmentStatementNode);
                                {
                                    t.N(SyntaxKind.VarList);
                                    {
                                        t.N(SyntaxKind.DotVar);
                                        {
                                            t.N(SyntaxKind.ParenPrefixExp);
                                            {
                                                t.N(SyntaxKind.OpenParen);
                                                t.N(SyntaxKind.DotVar);
                                                {
                                                    t.N(SyntaxKind.NameVar);
                                                    {
                                                        t.N(SyntaxKind.Identifier);
                                                    }
                                                    t.N(SyntaxKind.Dot);
                                                    t.N(SyntaxKind.Identifier);
                                                }
                                                t.N(SyntaxKind.MissingToken);
                                            }
                                            t.N(SyntaxKind.MissingToken);
                                            t.N(SyntaxKind.MissingToken);
                                        }
                                    }
                                    t.N(SyntaxKind.MissingToken);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.ParenPrefixExp);
                                        {
                                            t.N(SyntaxKind.OpenParen);
                                            t.N(SyntaxKind.NameVar);
                                            {
                                                t.N(SyntaxKind.Identifier);
                                            }
                                            t.N(SyntaxKind.MissingToken);
                                        }
                                        t.N(SyntaxKind.Comma);
                                        t.N(SyntaxKind.FunctionCallExp);
                                        {
                                            t.N(SyntaxKind.NameVar);
                                            {
                                                t.N(SyntaxKind.Identifier);
                                            }
                                            t.N(SyntaxKind.ParenArg);
                                            {
                                                t.N(SyntaxKind.OpenParen);
                                                t.N(SyntaxKind.ExpList);
                                                {
                                                    t.N(SyntaxKind.NameVar);
                                                    {
                                                        t.N(SyntaxKind.Identifier);
                                                    }
                                                }
                                                t.N(SyntaxKind.CloseParen);
                                            }
                                        }
                                    }
                                }
                            }
                            t.N(SyntaxKind.EndKeyword);
                        }
                    }
                    t.N(SyntaxKind.GlobalFunctionStatementNode);
                    {
                        t.N(SyntaxKind.FunctionKeyword);
                        t.N(SyntaxKind.FuncNameNode);
                        {
                            t.N(SyntaxKind.Identifier);
                            t.N(SyntaxKind.DotSeparatedNameList);
                        }
                        t.N(SyntaxKind.FuncBodyNode);
                        {
                            t.N(SyntaxKind.OpenParen);
                            t.N(SyntaxKind.NameListPar);
                            {
                                t.N(SyntaxKind.NameList);
                            }
                            t.N(SyntaxKind.CloseParen);
                            t.N(SyntaxKind.BlockNode);
                            {
                                t.N(SyntaxKind.FunctionCallStatementNode);
                                {
                                    t.N(SyntaxKind.NameVar);
                                    {
                                        t.N(SyntaxKind.Identifier);
                                    }
                                    t.N(SyntaxKind.ParenArg);
                                    {
                                        t.N(SyntaxKind.OpenParen);
                                        t.N(SyntaxKind.ExpList);
                                        {
                                            t.N(SyntaxKind.SimpleExpression);
                                            {
                                                t.N(SyntaxKind.String);
                                            }
                                        }
                                        t.N(SyntaxKind.CloseParen);
                                    }
                                }
                                t.N(SyntaxKind.SemiColonStatementNode);
                                {
                                    t.N(SyntaxKind.Semicolon);
                                }
                            }
                            t.N(SyntaxKind.EndKeyword);
                        }
                    }
                    t.N(SyntaxKind.GlobalFunctionStatementNode);
                    {
                        t.N(SyntaxKind.FunctionKeyword);
                        t.N(SyntaxKind.FuncNameNode);
                        {
                            t.N(SyntaxKind.Identifier);
                            t.N(SyntaxKind.DotSeparatedNameList);
                        }
                        t.N(SyntaxKind.FuncBodyNode);
                        {
                            t.N(SyntaxKind.OpenParen);
                            t.N(SyntaxKind.NameListPar);
                            {
                                t.N(SyntaxKind.NameList);
                                {
                                    t.N(SyntaxKind.Identifier);
                                    t.N(SyntaxKind.Comma);
                                    t.N(SyntaxKind.Identifier);
                                    t.N(SyntaxKind.Comma);
                                }
                            }
                            t.N(SyntaxKind.CloseParen);
                            t.N(SyntaxKind.BlockNode);
                            t.N(SyntaxKind.EndKeyword);
                        }
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }
        }
    }
}
