//C:\\Users\\t-kevimi\\Documents\\Engineering\\Lua Files for Testing\Assignments.lua
using LanguageModel.Tests.TestGeneration;
using LanguageService;
using Xunit;

namespace LanguageModel.Tests.GeneratedTestFiles
{
    class SmallIf_Generated
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.DoKeyword);
                        {
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.BinaryOperatorExpression);
                                {
                                    t.N(SyntaxKind.SimpleExpression);
                                    {
                                        t.N(SyntaxKind.String);
                                    }
                                    t.N(SyntaxKind.StringConcatOperator);
                                    t.N(SyntaxKind.SimpleExpression);
                                    {
                                        t.N(SyntaxKind.String);
                                    }
                                }
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.DotVar);
                                {
                                    t.N(SyntaxKind.NameVar);
                                    {
                                        t.N(SyntaxKind.Identifier);
                                    }
                                    t.N(SyntaxKind.Dot);
                                    t.N(SyntaxKind.Identifier);
                                }
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.BinaryOperatorExpression);
                                {
                                    t.N(SyntaxKind.DotVar);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                        t.N(SyntaxKind.Dot);
                                        t.N(SyntaxKind.Identifier);
                                    }
                                    t.N(SyntaxKind.PlusOperator);
                                    t.N(SyntaxKind.SimpleExpression);
                                    {
                                        t.N(SyntaxKind.Number);
                                    }
                                }
                            }
                        }
                    }
                    t.N(SyntaxKind.AssignmentStatementNode);
                    {
                        t.N(SyntaxKind.VarList);
                        {
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.Comma);
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                            }
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.NameVar);
                                {
                                    t.N(SyntaxKind.Identifier);
                                }
                            }
                        }
                        t.N(SyntaxKind.AssignmentOperator);
                        t.N(SyntaxKind.ExpList);
                        {
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.Comma);
                                t.N(SyntaxKind.SimpleExpression);
                                {
                                    t.N(SyntaxKind.Number);
                                }
                            }
                            t.N(SyntaxKind.SeparatedListElement);
                            {
                                t.N(SyntaxKind.BinaryOperatorExpression);
                                {
                                    t.N(SyntaxKind.SimpleExpression);
                                    {
                                        t.N(SyntaxKind.Number);
                                    }
                                    t.N(SyntaxKind.MultiplyOperator);
                                    t.N(SyntaxKind.NameVar);
                                    {
                                        t.N(SyntaxKind.Identifier);
                                    }
                                }
                            }
                        }
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }

        }
    }
}