//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.LanguageServices.Lua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.LanguageServices.Lua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new lines to multiline table constructors.
        /// </summary>
        public static string AddNewLinesToMultilineTableConstructorsCheckBoxContent {
            get {
                return ResourceManager.GetString("AddNewLinesToMultilineTableConstructorsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string FixedFunctionIndentationRadioContent {
            get {
                return ResourceManager.GetString("FixedFunctionIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string FixedTableIndentationRadioContent {
            get {
                return ResourceManager.GetString("FixedTableIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format on block.
        /// </summary>
        public static string FormatOnBlockCheckboxContent {
            get {
                return ResourceManager.GetString("FormatOnBlockCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting is applied on a Lua block after [Enter] is hit after the End keyword..
        /// </summary>
        public static string FormatOnBlockCheckboxToolTip {
            get {
                return ResourceManager.GetString("FormatOnBlockCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto format on [Enter].
        /// </summary>
        public static string FormatOnEnterCheckboxContent {
            get {
                return ResourceManager.GetString("FormatOnEnterCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting is applied on a line-by-line basis..
        /// </summary>
        public static string FormatOnEnterCheckboxToolTip {
            get {
                return ResourceManager.GetString("FormatOnEnterCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto format on paste.
        /// </summary>
        public static string FormatOnPasteCheckboxContent {
            get {
                return ResourceManager.GetString("FormatOnPasteCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting is applied on pasted text automattically..
        /// </summary>
        public static string FormatOnPasteCheckboxToolTip {
            get {
                return ResourceManager.GetString("FormatOnPasteCheckboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string FunctionIndentationGroupBoxHeader {
            get {
                return ResourceManager.GetString("FunctionIndentationGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralGroupBoxHeader {
            get {
                return ResourceManager.GetString("GeneralGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lines.
        /// </summary>
        public static string NewLinesGroupBoxHeader {
            get {
                return ResourceManager.GetString("NewLinesGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string RelativeFunctionIndentationRadioContent {
            get {
                return ResourceManager.GetString("RelativeFunctionIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string RelativeTableIndentationRadioContent {
            get {
                return ResourceManager.GetString("RelativeTableIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove spaces between index limits in a for loop.
        /// </summary>
        public static string RemoveSpaceBetweenIndexLimitsCheckBoxContent {
            get {
                return ResourceManager.GetString("RemoveSpaceBetweenIndexLimitsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert spaces after commas.
        /// </summary>
        public static string SpaceAfterCommasCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceAfterCommasCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a space before and after an assignment operator used for fields in table contructors.
        /// </summary>
        public static string SpaceBeforeAndAfterAssignmentOpsInFieldCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceBeforeAndAfterAssignmentOpsInFieldCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a space before and after an assignment operator used in for loop header.
        /// </summary>
        public static string SpaceBeforeAndAfterAssignmentOpsInForLoopCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceBeforeAndAfterAssignmentOpsInForLoopCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a space before and after an assignment operator used for statements.
        /// </summary>
        public static string SpaceBeforeAndAfterAssignmentOpsInStatementsCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceBeforeAndAfterAssignmentOpsInStatementsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a space before and after binary operations.
        /// </summary>
        public static string SpaceBeforeAndAfterBinOpsCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceBeforeAndAfterBinOpsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a space between a function name/keyword and an open parenthesis..
        /// </summary>
        public static string SpaceBetweenFunctionAndOpenParenCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceBetweenFunctionAndOpenParenCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert spaces on inside of curly braces.
        /// </summary>
        public static string SpaceInsideOfCurlyBracesCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceInsideOfCurlyBracesCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert spaces on the inside of parenthesis.
        /// </summary>
        public static string SpaceInsideOfParenthesisCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceInsideOfParenthesisCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert spaces on inside of square brackets.
        /// </summary>
        public static string SpaceInsideOfSquareBracketsCheckBoxContent {
            get {
                return ResourceManager.GetString("SpaceInsideOfSquareBracketsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string SpacingGroupBoxHeader {
            get {
                return ResourceManager.GetString("SpacingGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string TableIndentationGroupBoxHeader {
            get {
                return ResourceManager.GetString("TableIndentationGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapping.
        /// </summary>
        public static string WrappingGroupBoxHeader {
            get {
                return ResourceManager.GetString("WrappingGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap all single-line for loops.
        /// </summary>
        public static string WrapSingleLineForLoopsCheckBoxContent {
            get {
                return ResourceManager.GetString("WrapSingleLineForLoopsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap all single-line functions.
        /// </summary>
        public static string WrapSingleLineFunctionsCheckBoxContent {
            get {
                return ResourceManager.GetString("WrapSingleLineFunctionsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap all single-line table constructors.
        /// </summary>
        public static string WrapSingleLineTableConstructorsCheckBoxContent {
            get {
                return ResourceManager.GetString("WrapSingleLineTableConstructorsCheckBoxContent", resourceCulture);
            }
        }
    }
}
