//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.LanguageServices.Lua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.LanguageServices.Lua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string FixedFunctionIndentationRadioContent {
            get {
                return ResourceManager.GetString("FixedFunctionIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string FixedTableIndentationRadioContent {
            get {
                return ResourceManager.GetString("FixedTableIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format on block.
        /// </summary>
        internal static string FormatOnBlockCheckboxContent {
            get {
                return ResourceManager.GetString("FormatOnBlockCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting is applied on a Lua block after [Enter] is hit after the End keyword..
        /// </summary>
        internal static string FormatOnBlockCheckboxToolTips {
            get {
                return ResourceManager.GetString("FormatOnBlockCheckboxToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto format on [Enter].
        /// </summary>
        internal static string FormatOnEnterCheckboxContent {
            get {
                return ResourceManager.GetString("FormatOnEnterCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting is applied on a line-by-line basis..
        /// </summary>
        internal static string FormatOnEnterCheckboxToolTips {
            get {
                return ResourceManager.GetString("FormatOnEnterCheckboxToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto format on paste.
        /// </summary>
        internal static string FormatOnPasteCheckboxContent {
            get {
                return ResourceManager.GetString("FormatOnPasteCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting is applied on pasted text automattically..
        /// </summary>
        internal static string FormatOnPasteCheckboxToolTips {
            get {
                return ResourceManager.GetString("FormatOnPasteCheckboxToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string FunctionIndentationGroupBoxHeader {
            get {
                return ResourceManager.GetString("FunctionIndentationGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralGroupBoxHeader {
            get {
                return ResourceManager.GetString("GeneralGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        internal static string RelativeFunctionIndentationRadioContent {
            get {
                return ResourceManager.GetString("RelativeFunctionIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        internal static string RelativeTableIndentationRadioContent {
            get {
                return ResourceManager.GetString("RelativeTableIndentationRadioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string TableIndentationGroupBoxHeader {
            get {
                return ResourceManager.GetString("TableIndentationGroupBoxHeader", resourceCulture);
            }
        }
    }
}
