
using LanguageModel.Tests.TestGeneration;
using LanguageService;
using Xunit;
namespace LanguageModel.Tests.GeneratedTestFiles
{
    class IfStatement_Generated
    {
        [Fact]
        public void Test(Tester t)
        {
            t.N(SyntaxKind.ChunkNode);
            {
                t.N(SyntaxKind.BlockNode);
                {
                    t.N(SyntaxKind.IfStatementNode);
                    {
                        t.N(SyntaxKind.IfKeyword);
                        t.N(SyntaxKind.NameVar);
                        {
                            t.N(SyntaxKind.Identifier);
                        }
                        t.N(SyntaxKind.ThenKeyword);
                        t.N(SyntaxKind.BlockNode);
                        {
                            t.N(SyntaxKind.AssignmentStatementNode);
                            {
                                t.N(SyntaxKind.VarList);
                                {
                                    t.N(SyntaxKind.NameVar);
                                    {
                                        t.N(SyntaxKind.Identifier);
                                    }
                                }
                                t.N(SyntaxKind.AssignmentOperator);
                                t.N(SyntaxKind.ExpList);
                                {
                                    t.N(SyntaxKind.BinaryOperatorExpression);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                        t.N(SyntaxKind.PlusOperator);
                                        t.N(SyntaxKind.SimpleExpression);
                                        {
                                            t.N(SyntaxKind.Number);
                                        }
                                    }
                                }
                            }
                            t.N(SyntaxKind.SemiColonStatementNode);
                            {
                                t.N(SyntaxKind.Semicolon);
                            }
                        }
                        t.N(SyntaxKind.ElseBlockNode);
                        {
                            t.N(SyntaxKind.ElseKeyword);
                            t.N(SyntaxKind.BlockNode);
                            {
                                t.N(SyntaxKind.AssignmentStatementNode);
                                {
                                    t.N(SyntaxKind.VarList);
                                    {
                                        t.N(SyntaxKind.NameVar);
                                        {
                                            t.N(SyntaxKind.Identifier);
                                        }
                                    }
                                    t.N(SyntaxKind.AssignmentOperator);
                                    t.N(SyntaxKind.ExpList);
                                    {
                                        t.N(SyntaxKind.FunctionCallExp);
                                        {
                                            t.N(SyntaxKind.NameVar);
                                            {
                                                t.N(SyntaxKind.Identifier);
                                            }
                                            t.N(SyntaxKind.Colon);
                                            t.N(SyntaxKind.Identifier);
                                            t.N(SyntaxKind.ParenArg);
                                            {
                                                t.N(SyntaxKind.OpenParen);
                                                t.N(SyntaxKind.ExpList);
                                                t.N(SyntaxKind.CloseParen);
                                            }
                                        }
                                    }
                                }
                                t.N(SyntaxKind.SemiColonStatementNode);
                                {
                                    t.N(SyntaxKind.Semicolon);
                                }
                            }
                        }
                        t.N(SyntaxKind.EndKeyword);
                    }
                }
                t.N(SyntaxKind.EndOfFile);
            }
        }
    }
}
